### PR TITLE
introduce custom HandshakeError for open_websocket()

### LINKED ISSUE #116: can't discern connect vs. disconnect timeout
When there is a timeout raising TooSlowError, it's not obvious how to discern between connect and disconnect timeout for logging or raising a detailed error.

Perhaps trio-websocket should have a custom exception for timeout.

### PR DESCRIPTION
**Pull request by belm0**
`open_websocket()` now raises a custom `HandshakeError` for all handshake exceptions, including networking (`OSError`), client-side timeouts (`trio.TooSlowError`), and server rejection (`ConnectionRejected`).  Closes #116 and #118.

New exception hierarchy:

```
HandshakeError
  - ConnectionTimeout
  - DisconnectionTimeout
  - ConnectionRejected
```

### CODE REVIEW

**Comment by belm0** [comment]
`ConnectionRejected` should also derive from `HandshakeError`.

**Comment by mehaase** [comment]
This has a merge conflict with #124. Can you resolve that please?

The included test covers 16 of 18 new lines. Is it feasible to cover the last 2?

**Comment by belm0** [comment]
Regarding the code coverage, I'm actually not sure an OSError can happen during disconnect.  Maybe handling this case is unnecessary.

**Comment by belm0** [comment]
Test coverage is resolved.  I removed the newly added handling of OSError during disconnect, since it doesn't seem possible (Trio only passes OSError on accept or open, not send).

**Pull request merged**
