### PR TITLE
Fix setup.py project URL so it can be installed via pip git+.

### PR DESCRIPTION
**Pull request by belm0**

### CODE REVIEW

**Comment by belm0** [comment]
From @mehaase:
> Hey John, I am happy to merge HyperionGray/trio-websocket#5 but I don't think it will work. I am currently using a forked version of wsproto while I wait for several PRs to be reviewed on that project: https://github.com/mehaase/wsproto
> I couldn't find a way to list a git repo as a setup.py dependency, which is why the installation instructions have two steps (install wsproto fork, then install trio-websocket)

It looks straightforward to depend on git using a deprecated pip feature:  
  https://mike.zwobble.org/2013/05/adding-git-or-hg-or-svn-dependencies-in-setup-py/
(Pip will get proper support for git URL's in a release later this year.)

**Comment by belm0** [comment]
@mehaase please look again, I've found a simpler solution which doesn't require use of a deprecated pip flag (which isn't well-supported by tooling).

Simple pip install your wsproto version first.  Since trio-websocket doesn't supply a specific version, it will use the patched wsproto.

```
$ pip install git+https://github.com/mehaase/wsproto --upgrade
$ pip install git+https://github.com/HyperionGray/trio-websocket
...
Requirement already satisfied: wsproto in /.../python3.6/site-packages (from trio-websocket==0.0.1)
```

**Comment by belm0** [comment]
@mehaase I'm confused because all https://github.com/mehaase/wsproto has beyond upstream is one commit with doc changes.  So is it really a hard requirement?

**Comment by mehaase** [comment]
@belm0 Ah yes, sorry, I was working on `wsproto` locally. I just pushed my local changes.

The most important change that I have in my fork is this: https://github.com/python-hyper/wsproto/pull/50

The rest of the the changes are docs and minor things.

**Pull request closed without merging**
